# Generated by Django 2.1.3 on 2018-11-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
