# Generated by Django 2.1.3 on 2018-11-19 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('host', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=200)),
                ('education', models.CharField(default='', max_length=200)),
                ('income', models.CharField(default='', max_length=200)),
                ('language', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('other', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userVotes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Profile'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='userVotes',
            field=models.ManyToManyField(through='polls.Vote', to='polls.Votable'),
        ),
    ]
