# Generated by Django 2.1.3 on 2018-11-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionUser',
            field=models.ForeignKey(default='127.0.0.1:8000', on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
            preserve_default=False,
        ),
    ]
