# Generated by Django 2.1.3 on 2018-11-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181114_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votable',
            name='text',
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
