# Generated by Django 2.1.3 on 2018-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181125_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userAge',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
