# Generated by Django 2.1.3 on 2018-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181123_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userEducation',
        ),
        migrations.AddField(
            model_name='user',
            name='userEducation',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.RemoveField(
            model_name='user',
            name='userGender',
        ),
        migrations.AddField(
            model_name='user',
            name='userGender',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='user',
            name='userIncome',
        ),
        migrations.AddField(
            model_name='user',
            name='userIncome',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
