# Generated by Django 2.1.3 on 2018-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181124_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
